id: I4491AC69
legacy_id: P003227
ocr_import_info:
  bdrc_scan_id: W22081
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T20:22:35'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T15:36:21.603220+00:00'
last_modified: 2022-09-01 23:46:44.805968
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22081
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW22081
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། མཁའ་ཁྱབ་རྡོ་རྗེ། （དཔལ་སྤུངས་པར་མ།）
  author: ཀརྨ་པ ༡༥་མཁའ་ཁྱབ་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.7530950299412269
  ocr_word_median_confidence_index: 0.8299999833106995
quality: null
bases:
  I0364:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0364
      total_pages: 854
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I0364.txt
    statistics:
      ocr_word_median_confidence_index: 0.800000011920929
      ocr_word_mean_confidence_index: 0.7269013721474534
    legacy_id: v006
  I0365:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0365
      total_pages: 938
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I0365.txt
    statistics:
      ocr_word_median_confidence_index: 0.8299999833106995
      ocr_word_mean_confidence_index: 0.7607242640833078
    legacy_id: v007
  I0366:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0366
      total_pages: 936
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I0366.txt
    statistics:
      ocr_word_median_confidence_index: 0.8100000023841858
      ocr_word_mean_confidence_index: 0.7388406794472495
    legacy_id: v008
  I0367:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0367
      total_pages: 956
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I0367.txt
    statistics:
      ocr_word_median_confidence_index: 0.8700000047683716
      ocr_word_mean_confidence_index: 0.7870929657850759
    legacy_id: v009
  I0361:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0361
      total_pages: 944
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I0361.txt
    statistics:
      ocr_word_median_confidence_index: 0.8100000023841858
      ocr_word_mean_confidence_index: 0.7329226054079248
    legacy_id: v003
  I0360:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0360
      total_pages: 946
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I0360.txt
    statistics:
      ocr_word_median_confidence_index: 0.8299999833106995
      ocr_word_mean_confidence_index: 0.7519635391835455
    legacy_id: v002
  I0362:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0362
      total_pages: 1037
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I0362.txt
    statistics:
      ocr_word_median_confidence_index: 0.8500000238418579
      ocr_word_mean_confidence_index: 0.7703102426639111
    legacy_id: v004
  I0359:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0359
      total_pages: 908
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I0359.txt
    statistics:
      ocr_word_median_confidence_index: 0.8100000023841858
      ocr_word_mean_confidence_index: 0.7355587167017329
    legacy_id: v001
  I0363:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0363
      total_pages: 1013
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I0363.txt
    statistics:
      ocr_word_median_confidence_index: 0.8399999737739563
      ocr_word_mean_confidence_index: 0.7612604110959514
    legacy_id: v005
  I0368:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0368
      total_pages: 1007
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I0368.txt
    statistics:
      ocr_word_median_confidence_index: 0.8399999737739563
      ocr_word_mean_confidence_index: 0.7649421074087398
    legacy_id: v010
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
