id: I4491AC69
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T20:29:49+00:00'
last_modified: '2022-06-07T18:30:55.836775+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22081
  title: གསུང་འབུམ། མཁའ་ཁྱབ་རྡོ་རྗེ། （དཔལ་སྤུངས་པར་མ།）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    015E:
      image_group_id: I0359
      title: ''
      total_pages: 908
      order: 1
      base_file: 015E.txt
    9C96:
      image_group_id: I0360
      title: ''
      total_pages: 946
      order: 2
      base_file: 9C96.txt
    07BB:
      image_group_id: I0361
      title: ''
      total_pages: 944
      order: 3
      base_file: 07BB.txt
    A08B:
      image_group_id: I0362
      title: ''
      total_pages: 1037
      order: 4
      base_file: A08B.txt
    56EF:
      image_group_id: I0363
      title: ''
      total_pages: 1013
      order: 5
      base_file: 56EF.txt
    59DC:
      image_group_id: I0364
      title: ''
      total_pages: 854
      order: 6
      base_file: 59DC.txt
    DBC7:
      image_group_id: I0365
      title: ''
      total_pages: 938
      order: 7
      base_file: DBC7.txt
    8B8C:
      image_group_id: I0366
      title: ''
      total_pages: 936
      order: 8
      base_file: 8B8C.txt
    DF4F:
      image_group_id: I0367
      title: ''
      total_pages: 956
      order: 9
      base_file: DF4F.txt
    9E60:
      image_group_id: I0368
      title: ''
      total_pages: 1007
      order: 10
      base_file: 9E60.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
