id: P003227
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W22081
  title: གསུང་འབུམ། མཁའ་ཁྱབ་རྡོ་རྗེ། （དཔལ་སྤུངས་པར་མ།）
  author: ''
  volumes:
    ace4a9139e0e4116af265b1846de6353:
      image_group_id: I0359
      title: ''
      volume_number: 1
      total_pages: 908
      base_file: v001.txt
    46bc9b60aca342fbb96a621588706473:
      image_group_id: I0360
      title: ''
      volume_number: 2
      total_pages: 946
      base_file: v002.txt
    7638bef136ff48c6bcf6bf6c2ed899db:
      image_group_id: I0361
      title: ''
      volume_number: 3
      total_pages: 944
      base_file: v003.txt
    60d29ab4f79644c8aaf9fe4f2c190f95:
      image_group_id: I0362
      title: ''
      volume_number: 4
      total_pages: 1037
      base_file: v004.txt
    e1ffd4b055984b36a4c8cece802120cd:
      image_group_id: I0363
      title: ''
      volume_number: 5
      total_pages: 1013
      base_file: v005.txt
    7688694e1b8944fdb70690a871b0faa0:
      image_group_id: I0364
      title: ''
      volume_number: 6
      total_pages: 854
      base_file: v006.txt
    c287aee21c4c448fbeaf9739cc4c0eef:
      image_group_id: I0365
      title: ''
      volume_number: 7
      total_pages: 938
      base_file: v007.txt
    6a4e8b2f25194eef93a398c1bc29a937:
      image_group_id: I0366
      title: ''
      volume_number: 8
      total_pages: 936
      base_file: v008.txt
    c2645f004f4a41b1bb01053c41bc0f48:
      image_group_id: I0367
      title: ''
      volume_number: 9
      total_pages: 956
      base_file: v009.txt
    0e2a72461cc3459592dc5e2b051eab15:
      image_group_id: I0368
      title: ''
      volume_number: 10
      total_pages: 1007
      base_file: v010.txt
